---
abstract: 'simple PSGI-based pastebin-like website'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Web::Paste::Simple
name: Web-Paste-Simple
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::UUID: 0
  HTML::HTML5::Entities: 0
  JSON: 0
  Moo: 1.000000
  MooX::Types::MooseLike::Base: 0
  Path::Class::Dir: 0
  Path::Class::File: 0
  Plack::Request: 0
  Plack::Response: 0
  Text::Template: 0
  aliased: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Web-Paste-Simple
  homepage: https://metacpan.org/release/Web-Paste-Simple
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/web-paste-simple
version: 0.000_01
